### PR TITLE
Main block of memory index fixes to enable direct structure support

### PR DESCRIPTION
**Pull request by richardmcc**
Fixes for direct index support when writing memory structures to disk

### CODE REVIEW

**Comment by cmacdonald** [comment]
Richard is there any unit tests you can use to verify correctness?

**Comment by richardmcc** [comment]
I have a test, but not in JUnit format yet. These changes are primarally targeted at getting the direct index structures written correctly. So I guess the ideal case is where we write a simple structure and then run the standard direct structure battery of tests against it?

**Comment by cmacdonald** [comment]
Is there a way to create a MemoryIndex from a normal Index? That would be the easiest way to do the end-to-end tests.

But a unit test that simply puts some documents into the index, and checks it can read the contents would be sufficient - in the same way that https://github.com/terrier-org/terrier-core/blob/5.x/modules/tests/src/test/java/org/terrier/realtime/memory/TestMemoryIndex.java#L154 already works.

**Comment by richardmcc** [comment]
Added patch with direct index JUnit tests

**Comment by cmacdonald** [comment]
Hi Richard, for this one, travis wont build it would a rebase.
Could you:
 - rebase your pull request
 - remove the unused imports that Codacy mentions

**Comment by richardmcc** [comment]
I think I have re-based correctly

**Comment by richardmcc** [comment]
Nuking the remote for this entire branch and starting merge from scratch.

**Pull request closed without merging**
